/** T27 stress layout test: the exact graph generated by scripts/stress_test.py
 *  (1104 nodes / 3000 relations) must place every card without overlap, with
 *  the depth axis at the exact NODE_SIZE[1] gap, and must be deterministic.
 *
 *  Regenerate the fixture with:  python3 scripts/stress_test.py
 *  (writes fixtures/stress-graph.json) — without it the gate test below
 *  makes the failure LOUD instead of silently skipping the suite.
 */

import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { cardsOverlap, computeLayout, NODE_SIZE, rootIdOf } from "../layout";
import type { GraphNode } from "../types";

const FIXTURE = fileURLToPath(new URL("./fixtures/stress-graph.json", import.meta.url));
const hasFixture = existsSync(FIXTURE);
const nodes: GraphNode[] | null = hasFixture
  ? (JSON.parse(
      readFileSync(FIXTURE, "utf-8"),
    ) as { nodes: GraphNode[] }).nodes
  : null;

const PID = "stress-proj";

describe("stress layout (T27)", () => {
  it("fixture present (run scripts/stress_test.py to generate)", () => {
    expect(hasFixture, `fixture missing: ${FIXTURE}`).toBe(true);
    expect(nodes!.length).toBeGreaterThanOrEqual(1000);
  });

  if (nodes) {
    const n = nodes; // narrow for the registered tests

    it(`places all ${n.length} nodes plus the virtual root`, () => {
      const r = computeLayout(PID, n, new Set(), null);
      expect(r.positions.has(rootIdOf(PID))).toBe(true);
      for (const x of n) expect(r.positions.has(x.id)).toBe(true);
      expect(r.positions.size).toBe(n.length + 1);
    });

    it("never overlaps two placed cards (pairwise)", () => {
      const r = computeLayout(PID, n, new Set(), null);
      const list = [...r.positions.values()];
      for (let i = 0; i < list.length; i++) {
        for (let j = i + 1; j < list.length; j++) {
          expect(cardsOverlap(list[i], list[j]),
            `${list[i].id} ↔ ${list[j].id}`).toBe(false);
        }
      }
    });

    it("children sit exactly NODE_SIZE[1] right of their parent", () => {
      const r = computeLayout(PID, n, new Set(), null);
      let checked = 0;
      for (const x of n) {
        if (x.parent_id === null) continue;
        const p = r.positions.get(x.parent_id);
        const c = r.positions.get(x.id);
        if (!p || !c) continue;
        expect(c.x - p.x).toBe(NODE_SIZE[1]);
        checked++;
      }
      const tops = n.filter((x) => x.parent_id === null).length;
      expect(checked).toBe(n.length - tops);
    });

    it("is deterministic across runs", () => {
      const a = computeLayout(PID, n, new Set(), null);
      const b = computeLayout(PID, n, new Set(), null);
      expect(JSON.stringify([...a.positions])).toBe(JSON.stringify([...b.positions]));
    });

    it("branch focus shows only that branch's subtree", () => {
      const root = n.find((x) => x.parent_id === null)!;
      const branch = n.find((x) => x.parent_id === root.id)!;
      expect(branch).toBeDefined();
      const r = computeLayout(PID, n, new Set(), branch.id);
      const ids = new Set<string>([branch.id]);
      let grew = true;
      while (grew) {
        grew = false;
        for (const x of n) {
          if (x.parent_id && ids.has(x.parent_id) && !ids.has(x.id)) {
            ids.add(x.id);
            grew = true;
          }
        }
      }
      for (const id of ids) expect(r.visibleIds.has(id)).toBe(true);
      expect(r.visibleIds.size).toBe(ids.size);
      expect(r.positions.has(branch.id)).toBe(true);
    });

    it("folding a deep node keeps it and marks hidden direct children", () => {
      const deep = n.find((x) => (x.child_count ?? 0) >= 5);
      expect(deep).toBeDefined();
      const r = computeLayout(PID, n, new Set([deep!.id]), null);
      const placed = r.positions.get(deep!.id);
      expect(placed).toBeDefined();
      expect(placed!.hiddenCount).toBe(deep!.child_count);
      for (const x of n) {
        if (x.parent_id === deep!.id) expect(r.positions.has(x.id)).toBe(false);
      }
    });
  }
});