/** Chinese UI strings — the source of truth for the key set (DECISIONS §16).
 *  Values must stay byte-identical to the previously hardcoded literals so the
 *  zh-selector E2E suite and recorded behaviour don't shift. */

export const zh = {
  // ---- TokenGate -----------------------------------------------------------
  "gate.subtitle": "轻量科研演化地图 · 输入访问令牌打开工作站",
  "gate.token.placeholder": "访问令牌（Bearer token）",
  "gate.open": "打开",
  "gate.opening": "打开…",
  "gate.err.network": "无法连接服务器",
  "gate.note":
    "令牌只保存在页面内存中，刷新后需要重新输入；不会写入 Cookie、localStorage 或 URL。 本应用不需要任何模型 API Key。",

  // ---- EmptyProjects (App.tsx) ----------------------------------------------
  "empty.enter.or.create": "进入一个已有项目，或新建一个：",
  "empty.none": "还没有可用的项目——先创建第一个项目吧。",
  "empty.enter.btn": "进入「{name}」（v{rev}）",
  "empty.name.label": "项目名（1–100）",
  "empty.name.placeholder": "如：富锂锰基正极的循环衰减机制",
  "empty.objective.label": "研究目标（1–4000）",
  "empty.objective.placeholder": "你要回答什么问题？",
  "empty.create.err": "创建项目失败（请检查网络/令牌）",
  "empty.create": "创建项目",
  "empty.creating": "创建中…",
  "empty.refresh": "刷新项目列表",
  "empty.refreshing": "刷新中…",
  "empty.note":
    "项目数据保存在本服务器（SQLite 卷）。创建与编辑走同一条提交协议， 写操作都带令牌名身份（actor），不可伪造。",

  // ---- TopBar ---------------------------------------------------------------
  "topbar.switch.project": "切换项目",
  "topbar.new.project": "+ 项目",
  "topbar.new.project.title": "创建项目",
  "topbar.search.placeholder": "搜索标题/摘要/标签/观察/结论（中文子串可用）",
  "topbar.search.head": "搜索结果（点击 = 展开祖先并定位，不隐藏主树）",
  "topbar.search.count": " · 共 {n}",
  "topbar.search.loading": "检索中…",
  "topbar.search.empty": "无匹配（折叠不影响搜索覆盖）",
  "topbar.new.route": "+ 一级路线",
  "topbar.more.title": "更多：项目设置 / 适应当前图 / 近期变化 / 导出 / AI 接入",
  "topbar.menu.project.settings": "项目设置",
  "topbar.menu.fit": "适应当前图",
  "topbar.menu.show.archived": "显示已归档节点",
  "topbar.menu.hide.archived": "隐藏已归档节点 ✓",
  "topbar.menu.recent": "近期变化 ▾",
  "topbar.menu.no.commits": "暂无提交",
  "topbar.menu.export": "导出",
  "topbar.menu.export.title": "下载完整项目 JSON（含归档与历史）",
  "topbar.menu.ai": "AI 接入说明",
  "topbar.menu.lang.to_en": "切换为 English",
  "topbar.menu.lang.to_zh": "切换为 中文",
  "topbar.refresh": "刷新",
  "topbar.refresh.title": "手动检查记录是否变化",
  "topbar.actor": "身份: {actor}",
  "topbar.actor.title": "本次会话的访问者身份（由令牌决定，不可伪造）",
  "topbar.conn.version": " · v{v}",
  "topbar.conn.project": " · 项目 v{v}",
  "topbar.exit": "退出",
  "topbar.exit.title": "退出（清空页面内存中的令牌，需重新输入）",

  // ---- formatters (used across screens) -------------------------------------
  "common.first.level.node": "一级节点",

  // ---- enum display labels (API enums stay English; DECISIONS §16) ----------
  "status.unexplored": "未探索",
  "status.in_progress": "进行中",
  "status.promising": "有积极迹象",
  "status.supported": "当前条件下支持",
  "status.not_supported": "当前条件下不支持",
  "status.inconclusive": "尚不能判断",
  "kind.question": "问题",
  "kind.idea": "想法",
  "kind.attempt": "尝试",
  "kind.finding": "发现",
  "rel.related": "相关",
  "rel.motivates": "启发",
  "rel.supports": "支持",
  "rel.contradicts": "反对/不支持",
  "rel.depends_on": "依赖",

  // ---- Workspace：toast / 离开守卫 ------------------------------------------
  "ws.activity.load.fail": "关联加载失败",
  "ws.conflict.after.refresh": "刷新后发现同字段冲突，请在详情面板逐项核对",
  "ws.node.load.fail": "节点加载失败",
  "ws.load.fail": "加载失败",
  "ws.updates.loaded": "已载入最新记录",
  "ws.updates.load.fail": "载入更新失败",
  "ws.rebase.done": "已载入新版并重排草稿",
  "ws.rebase.fail": "重载失败",
  "ws.conflict.banner":
    "版本冲突：服务器已更新到 v{v}。你的草稿完整保留；点“载入新版并重排草稿”后再保存，不会静默覆盖他人修改。",
  "ws.conflict.toast": "版本冲突（已有他人提交）",
  "ws.err.missing": "（缺失：{items}）",
  "ws.err.missing.sep": "、",
  "ws.commit.fail": "提交失败",
  "ws.conflicts.unresolved": "还有 {n} 个字段与他人的修改冲突未处理：请在冲突区逐项选择后再保存",
  "ws.draft.stale": "草稿基于 v{base}，服务器已是 v{server}：先点“载入新版并重排草稿”再保存",
  "ws.confirm.draft": "有未保存的草稿。{what}草稿将丢失，确定继续？",
  "ws.confirm.leave.node": "离开当前节点，",
  "ws.confirm.switch.project": "切换项目，",
  "ws.confirm.new.project": "新建项目会离开当前项目，",
  "ws.confirm.exit": "退出当前项目，",
  "ws.created.rev": "已创建（记录 #{v}）",
  "ws.saved.rev": "已保存（v{v}）",
  "ws.create.fail": "创建失败",
  "ws.no.change": "记录目前无变化",
  "ws.refresh.fail": "刷新失败",
  "ws.loading.project": "正在加载项目…",
  "ws.export.done": "导出完成（含归档记录与全部历史）",
  "ws.export.fail": "导出失败",
  "ws.recent.archived": "该提交涉及的对象已归档",

  // ---- Workspace：提交摘要（会进入历史与「近期变化」，用户可见） -------------
  "ws.summary.update": "更新节点：{title}",
  "ws.summary.create.child": "新增子节点：{title}",
  "ws.summary.create.root": "新增一级路线：{title}",
  "ws.summary.move": "移动归属：{title}",
  "ws.summary.move.up": "上移：{title}",
  "ws.summary.move.down": "下移：{title}",
  "ws.summary.archive.node": "归档节点：{title}",
  "ws.summary.restore.node": "恢复节点：{title}",
  "ws.summary.relation.create": "建立关联：{source} {kind} → {target}…",
  "ws.summary.relation.update": "修改关联：{kind}",
  "ws.summary.relation.archive": "归档关联 {kind}",
  "ws.summary.relation.restore": "恢复关联 {kind}",
  "ws.summary.project.update": "更新项目名称与目标",

  // ---- 通用 / 模态共享 --------------------------------------------------------
  "common.cancel": "取消",
  "common.close": "关闭",
  "common.top.level.option": "（项目一级节点）",
  "ws.draft.heading": "新增节点",
  "ws.draft.unsaved": "未保存",
  "ws.draft.under.parent": "父级：",
  "ws.draft.parent.root": "一级路线（父级：项目一级节点）",

  // ---- 新建草稿会话（原 CreateNodeModal）------------------------------------
  // modal.create / modal.creating 仍用于草稿保存条（C2）；仅弹窗使用的字段文案
  // 已随弹窗退役删除，草稿表单复用 NodeFieldsForm 的 edit.* 字段标签。
  "modal.create": "创建",
  "modal.creating": "创建中…",

  // ---- ProjectModal / CreateRelationModal ---------------------------------------
  "modal.project.edit.title": "项目设置（名称与目标）",
  "modal.common.save": "保存",
  "modal.rel.title": "新增关联 · 起点：{from}（方向：本节点 → 目标）",
  "modal.rel.target.label": "选择目标（输入关键词缩小范围）",
  "modal.rel.target.ph": "如：溶剂热 / 高压 / 催化剂",
  "modal.rel.candidates": "— 从 {n} 个候选中选择 —",
  "modal.rel.kind.label": "关系类型（方向固定：本节点 → 目标）",
  "modal.rel.related": "相关 related（无向）",
  "modal.rel.motivates": "启发 motivates",
  "modal.rel.supports": "支持 supports",
  "modal.rel.contradicts": "反对/不支持 contradicts",
  "modal.rel.depends_on": "依赖 depends_on",
  "modal.rel.reason.label": "原因（一句话，1–500，必填）",
  "modal.rel.reason.ph": "例：该失败实验的负结果支持本节点的停止条件",
  "modal.rel.create": "建立关联",
  "modal.rel.note": "新增 supports / contradicts 不会自动改变任何节点状态；状态只能由研究者显式填写。",

  // ---- AiAccessModal --------------------------------------------------------------
  "ai.intro": "AI 与浏览器走同一条提交协议，不需要模型 API Key；所有持令牌者属于同一个受信任空间。",
  "ai.line.server": "服务器：{origin}（Authorization: Bearer <你的令牌>）",
  "ai.line.name": "项目名称：{name}",
  "ai.line.id": "项目 ID：{pid}",
  "ai.line.actor": "身份：每条提交的 actor 为令牌名（token_name），无法伪造",
  "ai.section.setup": "# 一次性配置（令牌只走环境变量，永不写进文件 / 日志 / 命令行参数）",
  "ai.line.token.export": "export RESEARCHMAP_TOKEN=\"<你的令牌>\"",
  "ai.section.read": "# 读取当前状态（不改数据）。以下三条都可直接粘贴运行：",
  "ai.section.focus": "# 聚焦某个节点（节点 ID 见卡片右键「复制节点深链接」末尾的 ?node=，或 graph 输出）：",
  "ai.section.search": "# 按关键词检索（中文子串可用）：",
  "ai.section.commit": "# 提交修改（请求文件必须含完整 request_id + expected_revision；先 --dry-run 校验）",
  "ai.section.409": "# 409 有四种，处理方式不同（退出码统一为 2，具体看 error.code）：",
  "ai.409.rev1": "#   REVISION_CONFLICT      期间有人提交过，锁的是整个项目的版本、不是单个对象；",
  "ai.409.rev2": "#                          本次一个字节都没写入。重读 context 后显式重写文件",
  "ai.409.rev3": "#                          （新的 expected_revision + 合并后的 operations）；",
  "ai.409.rev4": "#                          409 不留记录，沿用原 request_id 是合法的。",
  "ai.409.idem1": "#   IDEMPOTENCY_KEY_REUSED 该 request_id 已以不同内容成功提交过。要么原字节重放，",
  "ai.409.idem2": "#                          要么换新 request_id，切勿改字段后复用。",
  "ai.409.dup": "#   DUPLICATE_RELATION     同端点同类型的未归档关联已存在，改用 relation.update/restore。",
  "ai.409.pag": "#   PAGINATION_STALE       分页途中项目版本变了，放弃游标从头翻。",
  "ai.footer": "# 完整规范：docs/AI_USAGE.md（英文主入口）/ docs/AI_USAGE.zh-CN.md",
  "ai.copied": "接入信息已复制",
  "ai.copy.fail": "复制失败",
  "ai.copy": "复制接入信息",

  // ---- api（透传给 UI 的网络错误）---------------------------------------------
  "api.err.network": "无法连接服务器，请检查网络",

  // ---- SidePanel：草稿字段名 / 通用格式化 --------------------------------------
  "fld.kind": "类型",
  "fld.title": "标题",
  "fld.summary": "摘要",
  "fld.status": "状态",
  "fld.rationale": "为什么做 · 试法",
  "fld.finding": "直接观察",
  "fld.decision": "当前解释与决定",
  "fld.scope": "适用条件",
  "fld.details_md": "长说明",
  "fld.tags": "标签",
  "fld.evidence": "证据引用",
  "common.empty.paren": "（空）",
  "common.delete.title": "删除",
  "common.confirm": "确认",
  "common.list.sep": "、",
  "fmt.evidence.none": "（无证据）",
  "fmt.evidence.nolabel": "(无标签)",

  // ---- SidePanel：面板骨架 / 详情页 ---------------------------------------------
  "tab.detail": "详情",
  "tab.relations": "关联",
  "tab.history": "历史",
  "panel.loading": "加载中…",
  "panel.empty.select": "选择一个节点查看详情。",
  "panel.current.rev": "当前版本 v{n}",
  "panel.archived.paren": "（已归档）",
  "detail.updated": "更新于 {time} · 作者 {by}",
  "detail.camefrom": "你从关联目标定位过来。",
  "detail.back.to.from": "返回来源节点",
  "detail.dirty.hint": "有未保存的修改。切换节点或关闭面板会提醒；服务器版本变化不会覆盖草稿。",
  "detail.stale.hint": "本地草稿基于 v{base}，服务器已推进到 v{server}（期间有他人的提交）。",
  "detail.rebase.btn": "载入新版并重排草稿",
  "detail.stale.nosave": "重排前不能保存，避免静默覆盖他人修改。",
  "detail.conflict.hint": "提交时发生版本冲突：服务器已更新到 v{v}，你的草稿仍完整保留。",
  "detail.discard.btn": "放弃草稿",
  "detail.conflict.nosilent": "不会静默以你的旧版本覆盖他人修改。",
  "fld.scope.gate": "适用条件 scope",
  "fld.finding.gate": "直接观察 finding",
  "fld.decision.gate": "当前解释与决定 decision",
  "fld.evidence.gate": "至少一条证据 evidence",
  "detail.gate.hint": "状态为“{status}”要求填写：{items}。这只是记录完整性要求，不是自动科学审查。",
  "detail.save.blocked.conflicts": "还有 {n} 个冲突字段未处理：先在上方逐项选择",
  "detail.save.blocked.stale": "草稿基于旧版本：先点「载入新版并重排草稿」",
  "detail.cancel.revert": "取消（恢复原值）",
  "detail.collapse.edit": "收起编辑",
  "detail.dirty.chip": "有未保存的修改",
  "detail.edit": "编辑",
  "detail.add.child": "+ 子节点",
  "detail.archived.notice": "本节点已归档。恢复后相关 relations 才会重新渲染。",

  // ---- SidePanel：编辑表单 ---------------------------------------------------------
  "edit.mode.hint": "编辑模式 —— 只提交你改动的字段",
  "edit.kindstatus": "类型 / 状态",
  "edit.field.title": "标题（1–80 字符）",
  "edit.field.summary": "摘要：一句话研究增量（0–280）",
  "edit.field.rationale": "为什么做，试法是什么 rationale（0–2000）",
  "edit.field.finding": "直接观察到了什么 finding（0–2000，未确认写未知）",
  "edit.field.decision": "当前解释与下一步决定 decision（0–2000）",
  "edit.field.scope": "适用条件 scope（0–1000，红/绿状态必填）",
  "edit.field.tags": "标签（逗号分隔，每个 1–32 字符，最多 10 个）",
  "edit.field.details": "长说明 details_md（Markdown，0–30000）",
  "common.collapse": "收起",
  "common.expand": "展开",
  "edit.preview.back": "返回编辑（Markdown 渲染已禁用原始 HTML/脚本/外链图片）",
  "edit.preview.go": "预览渲染",
  "edit.table.insert": "插入表格",
  "edit.table.rows": "行数",
  "edit.table.cols": "列数",
  "edit.evidence.label": "证据引用（{n}/20）——只登记定位，系统不抓取、不执行、不代理读取",
  "edit.ev.inline": "inline 说明",
  "edit.ev.url": "url 链接",
  "edit.ev.path": "path 路径",
  "edit.ev.ph.url": "http(s)://…",
  "edit.ev.ph.path": "服务器/本机报告路径",
  "edit.ev.ph.inline": "一小段原始观察或说明",
  "edit.ev.note.ph": "note：限定语 / 可信度说明（如：样本少，不普适）",
  "edit.ev.add": "+ 添加证据",

  // ---- SidePanel：冲突解决（R02） ---------------------------------------------------
  "conflict.intro": "以下 {n} 个字段你与他人同时修改，已保留你的值。请逐项对比后选择，全部处理完才能保存——不会静默按任何一方覆盖。",
  "conflict.tag.base": "读取时（共同起点）",
  "conflict.tag.local": "你的草稿",
  "conflict.tag.server": "服务器（他人已提交）",
  "conflict.keep.mine": "保留我的",
  "conflict.use.server": "采用服务器",
  "conflict.manual": "我自己合并",

  // ---- SidePanel：阅读视图 ------------------------------------------------------------
  "read.sec.summary": "摘要 summary",
  "read.sec.rationale": "为什么做 · 试法 rationale",
  "read.sec.finding": "直接观察 finding",
  "read.sec.decision": "当前解释与决定 decision",
  "read.sec.scope": "适用条件 scope",
  "read.sec.tags": "标签 tags",
  "read.sec.evidence": "证据引用 evidence（{n}/20）",
  "read.sec.details": "长说明 details_md（Markdown）",
  "read.ev.inline": "行内记录",
  "read.ev.url": "url 链接",
  "read.ev.path": "path 路径",
  "read.ev.copy.title": "复制内容",
  "read.ev.copied": "已复制 ✓",
  "read.ev.copy": "复制",
  "read.ev.note": "note：{note}",

  // ---- SidePanel：组织与移动 -------------------------------------------------------------
  "org.title": "组织与移动",
  "org.move.up": "↑ 上移",
  "org.move.down": "↓ 下移",
  "org.move.btn": "移动归属",
  "org.archive.leafonly.title": "只能归档没有子节点的叶子节点",
  "org.archive.btn": "归档此节点（仅叶子）",
  "org.archive.reason.ph": "归档原因（必填）",
  "org.archive.confirm": "确认归档",
  "org.archive.blocked": "当前有子节点：请先移动或处理子节点，系统禁止级联删除。",
  "org.restore.btn": "恢复此节点",
  "org.restore.reason.ph": "恢复原因（必填）",
  "org.restore.confirm": "确认恢复",

  // ---- SidePanel：关联页 -----------------------------------------------------------------
  "rel.count": "共 {n} 条活跃关联",
  "rel.show.archived": "显示已归档",
  "rel.create.btn": "+ 新增关联（选择目标 → 类型 → 一句原因）",
  "rel.empty": "该节点暂无直接关联。",
  "rel.loadmore": "加载下一页（分页每页 20 条，完整可访问）",
  "rel.canvas.hint": "提示：点击画布虚线或上方条目可单独查看该关系；画布最多显示 {max} 条，超出部分在本列表可访问。",
  "rel.item.pick.title": "点我：在画布上单独显示这条关系线",
  "rel.item.other.archived": "（节点已归档）",
  "rel.locate": "定位",
  "rel.archive.btn": "归档关系",
  "rel.restore.btn": "恢复关系",
  "rel.edit.reason.ph": "一句原因（1–500）",
  "rel.edit.save": "保存修改",
  "rel.archive.reason.ph": "归档原因",
  "rel.restore.reason.ph": "恢复原因",
  "rel.restore.confirm": "确认恢复（需两端未归档）",

  // ---- SidePanel：历史页 ---------------------------------------------------------------------
  "hist.intro": "本节点的提交历史（含 other node 创建/移动等其他提交）。历史只记录不抹除；纠错请用新的提交。",
  "hist.empty": "该节点暂无历史提交。",
  "hist.client.paren": "（{label}）",
  "hist.loadmore": "加载更多（每页 20 条，最早 v{v} 之前）",
  "hist.created": "本提交创建了该节点。原始快照：",
  "hist.archived": "本提交归档了该节点。",
  "hist.restored": "本提交恢复了该节点。",
  "hist.notouch": "该提交不涉及本节点字段（可能是关系或顺序调整）。",
  "hist.copy.json": "复制本次提交的 JSON",
  "snap.empty": "（快照字段缺失）",
  "snap.finding": "观察",
  "hist.top.level": "（一级）",
  "hist.move": "位置变更：父级 {before} ⇒ {after}",
  "hist.move.order": " · 同级序号 {before} ⇒ {after}",

  // ---- relations.ts（关联描述句） ----------------------------------------------
  "rel.related.full": "相关：{title}",
  "rel.motivates.out": "本节点启发 {title}",
  "rel.motivates.in": "{title} 启发本节点",
  "rel.supports.out": "本节点支持 {title}",
  "rel.supports.in": "{title} 支持本节点",
  "rel.contradicts.out": "本节点反对 {title}",
  "rel.contradicts.in": "{title} 反对本节点",
  "rel.depends_on.out": "本节点依赖 {title}",
  "rel.depends_on.in": "{title} 依赖本节点",

  // ---- Canvas：更新横幅 / 面包屑 / 右键菜单 ---------------------------------------------------------
  "canvas.banner.pre": "有新的记录（服务器已更新到 ",
  "canvas.banner.post": "），是否载入？",
  "canvas.banner.load": "载入更新",
  "canvas.banner.later": "稍后",
  "canvas.banner.later.title": "不打断当前阅读：待载入状态保留，之后可随时点提示载入",
  "canvas.chip.title": "此前点击“稍后”，更新仍在等待载入",
  "canvas.chip.text": "待载入更新 v{n}",
  "canvas.chip.load": "载入",
  "canvas.chip.expand.title": "展开完整提示",
  "canvas.relcount": "画布显示 {shown} / {total} 条关联（完整列表见右侧「关联」页）",
  "canvas.breadcrumb.all": "项目全景",
  "canvas.breadcrumb.branch": "（分支视图）",
  "canvas.breadcrumb.back.title": "回到项目全景",
  "ctx.open.details": "打开详情",
  "ctx.add.child": "新增子节点",
  "ctx.expand.branch": "展开此分支",
  "ctx.collapse.branch": "折叠此分支",
  "ctx.only.branch": "只看这一分支",
  "ctx.copy.deeplink": "复制节点深链接",
  "ctx.deeplink.copied": "深链接已复制",
  "common.copy.fail": "复制失败",

  // ---- NodeCard --------------------------------------------------------------------------------------
  "node.archived": "已归档",
  "node.no.summary": "（无摘要）",
  "node.children.count": "子 {n}",
  "node.relations.count": "关联 {n}",
  "node.mark.new": "新增",
  "node.mark.changed": "已更新",
  "node.badge.updates": "分支内有更新 {n}",
  "node.fold.expand.title": "展开分支（隐藏 {n} 个直接子节点）",
  "node.fold.collapse.title": "折叠分支",

  // ---- ResizablePanel（A5） -------------------------------------------------------------
  "a5.collapse.title": "收起侧栏（宽度与收起状态会被记住）",
  "a5.expand.title": "展开侧栏",
  "a5.handle.label": "调整侧栏宽度（←加宽，→收窄，回车/拖动同样有效）",
  "a5.locate.chip": "定位当前节点",
  "a5.rail.dirty.title": "侧栏已收起，但有未保存的草稿",

  // ---- ViewToolbar（A6，一键展开/折叠） ------------------------------------------------
  "a6.expand.all": "全部展开 · {n}",
  "a6.expand.all.title": "清空折叠集（当前可见 {n} 个节点；不改「只看这一分支」的过滤）",
  "a6.collapse.all": "全部折叠",
  "a6.collapse.all.title": "折叠全部有子节点的可见节点，只留各支顶层",
  "a6.more.title": "更多展开/折叠工具",
  "a6.expand.level": "展开到第 {n} 层",
  "a6.expand.subtree": "展开选中节点的分支",
  "a6.expand.subtree.title": "清除选中节点子树内的全部折叠（不含子树外的折叠）",
  "a6.restore": "恢复上次",
  "a6.restore.title": "回到上一批工具执行前的折叠状态（卡片上的手动折叠不参与）",

  // ---- TopBar 自适应三档（A7，full → more → icon） ------------------------------------
  "a7.search.title": "搜索节点",

  // ---- 信息密度三档（B1/B4，DECISIONS §14） -------------------------------------------
  "density.reading": "阅读",
  "density.compact": "精简",
  "density.overview": "概览",
  "density.auto": "自动",
  "b1.legend": "图例",
  "b1.low.on": "开启低干扰模式",
  "b1.low.off": "关闭低干扰模式",
  "b1.low.title": "隐藏卡片的标签、关联数与子节点数（悬停关系线仍可看标签）",
  "b1.zoom.locate": "放大定位",

  // ---- 布局策略（B2，DECISIONS §15） ---------------------------------------------------
  "layout.h": "横向树",
  "layout.v": "纵向树",
  "layout.outline": "大纲",
  "vt.layout.title": "切换画布布局（每个布局分别记住折叠/分支/视口）",
} as const;

export type DictKey = keyof typeof zh;
