/** English UI strings. The type pins every key of dict.zh — a missing key here
 *  is a compile error, so `npm run build` enforces dictionary parity. */

import type { zh } from "./dict.zh";

export const en: Record<keyof typeof zh, string> = {
  // ---- TokenGate -----------------------------------------------------------
  "gate.subtitle": "Lightweight research evolution map · enter your access token to open the workspace",
  "gate.token.placeholder": "Access token (Bearer token)",
  "gate.open": "Open",
  "gate.opening": "Opening…",
  "gate.err.network": "Cannot reach the server",
  "gate.note":
    "The token is kept in page memory only; a refresh requires re-entry. It is never written to cookies, localStorage, or the URL. This app needs no model API key.",

  // ---- EmptyProjects (App.tsx) ----------------------------------------------
  "empty.enter.or.create": "Enter an existing project, or create one:",
  "empty.none": "No projects yet — create your first project.",
  "empty.enter.btn": "Enter \"{name}\" (v{rev})",
  "empty.name.label": "Project name (1–100)",
  "empty.name.placeholder": "e.g. Li-rich Mn-based cathode degradation mechanism",
  "empty.objective.label": "Research goal (1–4000)",
  "empty.objective.placeholder": "What question are you trying to answer?",
  "empty.create.err": "Failed to create the project (check network/token)",
  "empty.create": "Create project",
  "empty.creating": "Creating…",
  "empty.refresh": "Refresh project list",
  "empty.refreshing": "Refreshing…",
  "empty.note":
    "Project data is stored on this server (SQLite volume). Creation and edits go through the same commit protocol; every write carries the token's identity (actor) and cannot be forged.",

  // ---- TopBar ---------------------------------------------------------------
  "topbar.switch.project": "Switch project",
  "topbar.new.project": "+ Project",
  "topbar.new.project.title": "Create project",
  "topbar.search.placeholder": "Search titles/summaries/tags/observations/findings (substrings work)",
  "topbar.search.head": "Search results (click = expand ancestors and locate; the main tree stays visible)",
  "topbar.search.count": " · {n} total",
  "topbar.search.loading": "Searching…",
  "topbar.search.empty": "No matches (folding does not limit search)",
  "topbar.new.route": "+ Top-level route",
  "topbar.more.title": "More: project settings / fit map / recent changes / export / AI access",
  "topbar.menu.project.settings": "Project settings",
  "topbar.menu.fit": "Fit current map",
  "topbar.menu.show.archived": "Show archived nodes",
  "topbar.menu.hide.archived": "Hide archived nodes ✓",
  "topbar.menu.recent": "Recent changes ▾",
  "topbar.menu.no.commits": "No commits yet",
  "topbar.menu.export": "Export",
  "topbar.menu.export.title": "Download the full project JSON (incl. archive and history)",
  "topbar.menu.ai": "AI access guide",
  "topbar.menu.lang.to_en": "Switch to English",
  "topbar.menu.lang.to_zh": "切换为 中文",
  "topbar.refresh": "Refresh",
  "topbar.refresh.title": "Manually check whether records changed",
  "topbar.actor": "Identity: {actor}",
  "topbar.actor.title": "Who is signed in for this session (decided by the token; cannot be forged)",
  "topbar.conn.version": " · record #{v}",
  "topbar.conn.project": " · project record #{v}",
  "topbar.exit": "Exit",
  "topbar.exit.title": "Exit (clears the in-memory token; you will re-enter it)",

  // ---- formatters (used across screens) -------------------------------------
  "common.first.level.node": "top-level node",

  // ---- enum display labels ---------------------------------------------------
  "status.unexplored": "Unexplored",
  "status.in_progress": "In progress",
  "status.promising": "Promising",
  "status.supported": "Supported (current conditions)",
  "status.not_supported": "Not supported (current conditions)",
  "status.inconclusive": "Inconclusive",
  "kind.question": "Question",
  "kind.idea": "Idea",
  "kind.attempt": "Attempt",
  "kind.finding": "Finding",
  "rel.related": "Related",
  "rel.motivates": "Motivates",
  "rel.supports": "Supports",
  "rel.contradicts": "Contradicts",
  "rel.depends_on": "Depends on",

  // ---- Workspace: toasts / leave guards --------------------------------------
  "ws.activity.load.fail": "Failed to load relations",
  "ws.conflict.after.refresh": "Same-field conflicts were found after the refresh — review them one by one in the details panel",
  "ws.node.load.fail": "Failed to load the node",
  "ws.load.fail": "Failed to load",
  "ws.updates.loaded": "Latest records loaded",
  "ws.updates.load.fail": "Failed to load updates",
  "ws.rebase.done": "Latest record loaded and draft rebased",
  "ws.rebase.fail": "Reload failed",
  "ws.conflict.banner":
    "Save conflict: someone has committed record #{v}. Your draft is fully preserved; click “Load latest record and rebase draft” before saving — nothing is silently overwritten.",
  "ws.conflict.toast": "Revision conflict (someone else committed in the meantime)",
  "ws.err.missing": " (missing: {items})",
  "ws.err.missing.sep": ", ",
  "ws.commit.fail": "Commit failed",
  "ws.conflicts.unresolved": "{n} field(s) still conflict with someone else's edits: pick a resolution for each in the conflict area before saving",
  "ws.draft.stale": "Draft is based on record #{base} but the server is at record #{server}: click “Load latest record and rebase draft” first, then save",
  "ws.confirm.draft": "You have an unsaved draft. {what}the draft will be lost. Continue?",
  "ws.confirm.leave.node": "Leaving the current node, ",
  "ws.confirm.switch.project": "Switching project, ",
  "ws.confirm.new.project": "Creating a new project leaves the current one, ",
  "ws.confirm.exit": "Exiting the current project, ",
  "ws.created.rev": "Created (record #{v})",
  "ws.saved.rev": "Saved (record #{v})",
  "ws.create.fail": "Failed to create",
  "ws.no.change": "Records unchanged so far",
  "ws.refresh.fail": "Refresh failed",
  "ws.loading.project": "Loading project…",
  "ws.export.done": "Export complete (includes archived records and full history)",
  "ws.export.fail": "Export failed",
  "ws.recent.archived": "The objects touched by that commit have been archived",

  // ---- Workspace: commit summaries (land in history and recent changes) ------
  "ws.summary.update": "Update node: {title}",
  "ws.summary.create.child": "Add child node: {title}",
  "ws.summary.create.root": "Add top-level route: {title}",
  "ws.summary.move": "Re-parent: {title}",
  "ws.summary.move.up": "Move up: {title}",
  "ws.summary.move.down": "Move down: {title}",
  "ws.summary.archive.node": "Archive node: {title}",
  "ws.summary.restore.node": "Restore node: {title}",
  "ws.summary.relation.create": "Create relation: {source} {kind} → {target}…",
  "ws.summary.relation.update": "Edit relation: {kind}",
  "ws.summary.relation.archive": "Archive relation {kind}",
  "ws.summary.relation.restore": "Restore relation {kind}",
  "ws.summary.project.update": "Update project name and objective",

  // ---- shared modal / common strings ------------------------------------------
  "common.cancel": "Cancel",
  "common.close": "Close",
  "common.top.level.option": "(project top-level nodes)",
  "ws.draft.heading": "New node",
  "ws.draft.unsaved": "Unsaved",
  "ws.draft.under.parent": "Under:",
  "ws.draft.parent.root": "Top-level route (parent: project root)",

  // ---- create draft session (formerly CreateNodeModal) ------------------------------
  // Keys modal.create / modal.creating stay in use on the draft save bar (C2);
  // the old modal-only field labels died with the modal — the draft form reuses
  // the edit.* field labels via NodeFieldsForm.
  "modal.create": "Create",
  "modal.creating": "Creating…",

  // ---- ProjectModal / CreateRelationModal ------------------------------------------
  "modal.project.edit.title": "Project settings (name and objective)",
  "modal.common.save": "Save",
  "modal.rel.title": "New relation · from: {from} (direction: this node → target)",
  "modal.rel.target.label": "Pick a target (type keywords to narrow down)",
  "modal.rel.target.ph": "e.g. solvothermal / high pressure / catalyst",
  "modal.rel.candidates": "— choose from {n} candidates —",
  "modal.rel.kind.label": "Relation type (direction fixed: this node → target)",
  "modal.rel.related": "Related · related (undirected)",
  "modal.rel.motivates": "Motivates · motivates",
  "modal.rel.supports": "Supports · supports",
  "modal.rel.contradicts": "Contradicts · contradicts",
  "modal.rel.depends_on": "Depends on · depends_on",
  "modal.rel.reason.label": "Reason (one sentence, 1–500, required)",
  "modal.rel.reason.ph": "e.g. the negative result of that failed experiment supports this node's stop condition",
  "modal.rel.create": "Create relation",
  "modal.rel.note": "Creating supports / contradicts never changes any node status; only researchers set statuses explicitly.",

  // ---- AiAccessModal ------------------------------------------------------------------
  "ai.intro": "AI tools use the same commit protocol as the browser and need no model API key; every token holder is part of the same trusted space.",
  "ai.line.server": "Server: {origin} (Authorization: Bearer <your token>)",
  "ai.line.name": "Project name: {name}",
  "ai.line.id": "Project ID: {pid}",
  "ai.line.actor": "Identity: every commit's actor is the token name (token_name) and cannot be forged",
  "ai.section.setup": "# One-time setup (the token only travels through environment variables, never into files / logs / command-line arguments)",
  "ai.line.token.export": "export RESEARCHMAP_TOKEN=\"<your token>\"",
  "ai.section.read": "# Read the current state (no writes). All three commands below can be pasted and run as-is:",
  "ai.section.focus": "# Focus a node (the node ID is at the end of the ?node= from the card's right-click “Copy node deep link”, or in the graph output):",
  "ai.section.search": "# Search by keyword (CJK substrings work):",
  "ai.section.commit": "# Commit changes (the request file must contain a complete request_id + expected_revision; validate with --dry-run first)",
  "ai.section.409": "# There are four kinds of 409, handled differently (exit code is always 2; check error.code):",
  "ai.409.rev1": "#   REVISION_CONFLICT      someone committed in the meantime; the lock covers the whole project's revision, not a single object;",
  "ai.409.rev2": "#                          not a single byte was written this time. Re-read context, then explicitly rewrite the file",
  "ai.409.rev3": "#                          (new expected_revision + the merged operations);",
  "ai.409.rev4": "#                          a 409 leaves no record, so reusing the original request_id is legal.",
  "ai.409.idem1": "#   IDEMPOTENCY_KEY_REUSED this request_id already succeeded with different content. Either replay the original bytes,",
  "ai.409.idem2": "#                          or use a new request_id — never reuse it after editing fields.",
  "ai.409.dup": "#   DUPLICATE_RELATION     an unarchived relation with the same endpoints and type already exists; use relation.update/restore.",
  "ai.409.pag": "#   PAGINATION_STALE       the project revision changed mid-pagination; drop the cursor and page from the start.",
  "ai.footer": "# Full spec: docs/AI_USAGE.md (English entry) / docs/AI_USAGE.zh-CN.md",
  "ai.copied": "Access info copied",
  "ai.copy.fail": "Copy failed",
  "ai.copy": "Copy access info",

  // ---- api (network error surfaced to the UI) --------------------------------
  "api.err.network": "Cannot reach the server — check your network",

  // ---- SidePanel: draft field names / common formatting ------------------------
  "fld.kind": "Kind",
  "fld.title": "Title",
  "fld.summary": "Summary",
  "fld.status": "Status",
  "fld.rationale": "Rationale",
  "fld.finding": "Finding",
  "fld.decision": "Decision",
  "fld.scope": "Scope",
  "fld.details_md": "Long description",
  "fld.tags": "Tags",
  "fld.evidence": "Evidence",
  "common.empty.paren": "(empty)",
  "common.delete.title": "Delete",
  "common.confirm": "Confirm",
  "common.list.sep": ", ",
  "fmt.evidence.none": "(no evidence)",
  "fmt.evidence.nolabel": "(no label)",

  // ---- SidePanel: panel chrome / detail tab --------------------------------------
  "tab.detail": "Details",
  "tab.relations": "Relations",
  "tab.history": "History",
  "panel.loading": "Loading…",
  "panel.empty.select": "Select a node to see its details.",
  "panel.current.rev": "Current revision v{n}",
  "panel.archived.paren": "(archived)",
  "detail.updated": "Updated {time} · by {by}",
  "detail.camefrom": "You jumped here from a related node.",
  "detail.back.to.from": "Back to source node",
  "detail.dirty.hint": "You have unsaved changes. Switching nodes or closing the panel will warn; server updates never overwrite your draft.",
  "detail.stale.hint": "This draft is based on record #{base}; the server has moved to record #{server} (someone committed in between).",
  "detail.rebase.btn": "Load latest record & rebase draft",
  "detail.stale.nosave": "Save is disabled until you rebase, so no one's changes get silently overwritten.",
  "detail.conflict.hint": "A save conflict happened on commit: someone committed record #{v}; your draft is still fully preserved.",
  "detail.discard.btn": "Discard draft",
  "detail.conflict.nosilent": "Your older version is never silently applied over someone else's changes.",
  "fld.scope.gate": "Scope",
  "fld.finding.gate": "Finding",
  "fld.decision.gate": "Decision",
  "fld.evidence.gate": "At least one piece of evidence",
  "detail.gate.hint": "The status “{status}” requires: {items}. This is a record-completeness requirement, not an automatic scientific review.",
  "detail.save.blocked.conflicts": "{n} conflicted field(s) unresolved: resolve them above first",
  "detail.save.blocked.stale": "Draft is based on an older record: click “Load latest record & rebase draft” first",
  "detail.cancel.revert": "Cancel (revert)",
  "detail.collapse.edit": "Collapse editor",
  "detail.dirty.chip": "Unsaved changes",
  "detail.edit": "Edit",
  "detail.add.child": "+ Child node",
  "detail.archived.notice": "This node is archived. Its relations render again once restored.",

  // ---- SidePanel: edit form ---------------------------------------------------------
  "edit.mode.hint": "Edit mode — only the fields you changed get committed",
  "edit.kindstatus": "Kind / Status",
  "edit.field.title": "Title (1–80 characters)",
  "edit.field.summary": "Summary: one-sentence research increment (0–280)",
  "edit.field.rationale": "Why this, and the approach — rationale (0–2000)",
  "edit.field.finding": "What was directly observed — finding (0–2000; write “unknown” if unconfirmed)",
  "edit.field.decision": "Current interpretation and next decision (0–2000)",
  "edit.field.scope": "Scope of applicability (0–1000; required for red/green statuses)",
  "edit.field.tags": "Tags (comma-separated, 1–32 characters each, at most 10)",
  "edit.field.details": "Long description details_md (Markdown, 0–30000)",
  "common.collapse": "Collapse",
  "common.expand": "Expand",
  "edit.preview.back": "Back to editing (Markdown rendering disables raw HTML / scripts / remote images)",
  "edit.preview.go": "Preview render",
  "edit.table.insert": "Insert table",
  "edit.table.rows": "Rows",
  "edit.table.cols": "Columns",
  "att.insert": "Insert image",
  "att.uploading": "Uploading…",
  "att.upload.failed": "Image upload failed: ",
  "att.upload.notimage": "Only image files can be uploaded",
  "att.upload.noproject": "Project not ready; upload unavailable",
  "att.loading": "Loading image…",
  "att.error": "Failed to load image",
  "att.zoom": "Zoom image {alt}",
  "att.lightbox.label": "Image preview",
  "att.lightbox.close": "Close full-size view",
  "ver.label": "Research versions",
  "ver.none.yet": "No research versions yet",
  "ver.unassigned": "Unassigned",
  "ver.archived": "archived",
  "att.external": "External image (not loaded): ",
  "edit.evidence.label": "Evidence ({n}/20) — pointers only; the system never fetches, executes or proxies reads",
  "edit.ev.inline": "Inline note",
  "edit.ev.url": "URL link",
  "edit.ev.path": "Path",
  "edit.ev.ph.url": "http(s)://…",
  "edit.ev.ph.path": "Server / local report path",
  "edit.ev.ph.inline": "A short piece of raw observation or explanation",
  "edit.ev.note.ph": "note: qualifiers / confidence (e.g. small sample, not general)",
  "edit.ev.add": "+ Add evidence",

  // ---- SidePanel: conflict resolution (R02) -------------------------------------------
  "conflict.intro": "{n} field(s) were changed by you and someone else at the same time; your values are kept for now. Compare each row and pick — nothing is saved until all are resolved, and neither side is applied silently.",
  "conflict.tag.base": "As read (common base)",
  "conflict.tag.local": "Your draft",
  "conflict.tag.server": "Server (already committed)",
  "conflict.keep.mine": "Keep mine",
  "conflict.use.server": "Use server",
  "conflict.manual": "I'll merge it myself",

  // ---- SidePanel: read view --------------------------------------------------------
  "read.sec.summary": "Summary",
  "read.sec.rationale": "Rationale",
  "read.sec.finding": "Finding",
  "read.sec.decision": "Decision",
  "read.sec.scope": "Scope",
  "read.sec.tags": "Tags",
  "read.sec.evidence": "Evidence ({n}/20)",
  "read.sec.details": "Long description details_md (Markdown)",
  "read.ev.inline": "Inline note",
  "read.ev.url": "URL link",
  "read.ev.path": "Path",
  "read.ev.copy.title": "Copy content",
  "read.ev.copied": "Copied ✓",
  "read.ev.copy": "Copy",
  "read.ev.note": "note: {note}",

  // ---- SidePanel: organize & move ------------------------------------------------------
  "org.title": "Organize & move",
  "org.move.up": "↑ Up",
  "org.move.down": "↓ Down",
  "org.move.btn": "Re-parent",
  "org.archive.leafonly.title": "Only leaf nodes without children can be archived",
  "org.archive.btn": "Archive node (leaves only)",
  "org.archive.reason.ph": "Archive reason (required)",
  "org.archive.confirm": "Confirm archive",
  "org.archive.blocked": "This node still has children: move or handle them first; cascading deletes are forbidden.",
  "org.restore.btn": "Restore node",
  "org.restore.reason.ph": "Restore reason (required)",
  "org.restore.confirm": "Confirm restore",

  // ---- SidePanel: relations tab ---------------------------------------------------------
  "rel.count": "{n} active relation(s)",
  "rel.show.archived": "Show archived",
  "rel.create.btn": "+ New relation (target → type → one-line reason)",
  "rel.empty": "This node has no direct relations yet.",
  "rel.loadmore": "Load next page (20 per page; everything stays reachable)",
  "rel.canvas.hint": "Tip: click a dashed canvas line or an entry above to show just that relation; the canvas shows at most {max}, the rest stays reachable in this list.",
  "rel.item.pick.title": "Click: show only this relation line on the canvas",
  "rel.item.other.archived": "(node archived)",
  "rel.locate": "Locate",
  "rel.archive.btn": "Archive relation",
  "rel.restore.btn": "Restore relation",
  "rel.edit.reason.ph": "One-line reason (1–500)",
  "rel.edit.save": "Save changes",
  "rel.archive.reason.ph": "Archive reason",
  "rel.restore.reason.ph": "Restore reason",
  "rel.restore.confirm": "Confirm restore (both ends must be unarchived)",

  // ---- SidePanel: history tab ---------------------------------------------------------------
  "hist.intro": "This node's commit history (including other-object commits like creates/moves). History only records, never erases; correct things with new commits.",
  "hist.empty": "No commits for this node yet.",
  "hist.client.paren": " ({label})",
  "hist.loadmore": "Load more (20 per page, before record #{v})",
  "hist.created": "This commit created the node. Original snapshot:",
  "hist.archived": "This commit archived the node.",
  "hist.restored": "This commit restored the node.",
  "hist.notouch": "This commit does not touch this node's fields (probably a relation or ordering change).",
  "hist.copy.json": "Copy commit JSON",
  "snap.empty": "(snapshot fields missing)",
  "snap.finding": "Observation",
  "hist.top.level": "(top level)",
  "hist.move": "Moved: parent {before} ⇒ {after}",
  "hist.move.order": " · sibling index {before} ⇒ {after}",

  // ---- relations.ts (relation description sentences) ------------------------------------------
  "rel.related.full": "Related: {title}",
  "rel.motivates.out": "This node motivates {title}",
  "rel.motivates.in": "{title} motivates this node",
  "rel.supports.out": "This node supports {title}",
  "rel.supports.in": "{title} supports this node",
  "rel.contradicts.out": "This node contradicts {title}",
  "rel.contradicts.in": "{title} contradicts this node",
  "rel.depends_on.out": "This node depends on {title}",
  "rel.depends_on.in": "{title} depends on this node",

  // ---- Canvas: update banner / breadcrumbs / context menu -----------------------------------------
  "canvas.banner.pre": "New records (the server moved to ",
  "canvas.banner.post": ") — load them now?",
  "canvas.banner.load": "Load updates",
  "canvas.banner.later": "Later",
  "canvas.banner.later.title": "Keeps reading uninterrupted: the pending update stays until you load it",
  "canvas.chip.title": "You clicked “Later”; the update is still waiting to be loaded",
  "canvas.chip.text": "Pending update v{n}",
  "canvas.chip.load": "Load",
  "canvas.chip.expand.title": "Expand full banner",
  "canvas.relcount": "Showing {shown} / {total} relations on canvas (full list in the Relations tab)",
  "canvas.breadcrumb.all": "Project overview",
  "canvas.breadcrumb.branch": "(branch view)",
  "canvas.breadcrumb.back.title": "Back to project overview",
  "ctx.open.details": "Open details",
  "ctx.add.child": "Add child node",
  "ctx.expand.branch": "Expand this branch",
  "ctx.collapse.branch": "Collapse this branch",
  "ctx.only.branch": "Focus this branch",
  "ctx.copy.deeplink": "Copy node deep link",
  "ctx.deeplink.copied": "Deep link copied",
  "common.copy.fail": "Copy failed",

  // ---- NodeCard ------------------------------------------------------------------------------------
  "node.archived": "Archived",
  "node.no.summary": "(no summary)",
  "node.children.count": "sub {n}",
  "node.relations.count": "rel {n}",
  "node.mark.new": "New",
  "node.mark.changed": "Updated",
  "node.badge.updates": "{n} updates in branch",
  "node.fold.expand.title": "Expand branch ({n} direct children hidden)",
  "node.fold.collapse.title": "Collapse branch",

  "a5.collapse.title": "Collapse side panel (width and state are remembered)",
  "a5.expand.title": "Expand side panel",
  "a5.handle.label": "Resize side panel (← wider, → narrower)",
  "a5.locate.chip": "Locate current node",
  "a5.rail.dirty.title": "Panel is collapsed, but you have an unsaved draft",

  "a6.expand.all": "Expand all · {n}",
  "a6.expand.all.title": "Clear the fold set ({n} nodes visible; the branch filter is untouched)",
  "a6.collapse.all": "Collapse all",
  "a6.collapse.all.title": "Fold every visible node with children, leaving branch tops only",
  "a6.more.title": "More expand/collapse tools",
  "a6.expand.level": "Expand to level {n}",
  "a6.expand.subtree": "Expand selected node's branch",
  "a6.expand.subtree.title": "Clear all folds inside the selected node's subtree (folds outside stay)",
  "a6.restore": "Restore last",
  "a6.restore.title": "Return to the fold state before the last batch tool (card-level manual folds excluded)",

  "a7.search.title": "Search nodes",

  "density.reading": "Reading",
  "density.compact": "Compact",
  "density.overview": "Overview",
  "density.auto": "Auto",
  "b1.legend": "Legend",
  "b1.low.on": "Turn on low-interference mode",
  "b1.low.off": "Turn off low-interference mode",
  "b1.low.title": "Hide card labels, tags and relation/child counts (hovering a relation still shows its label)",
  "b1.zoom.locate": "Zoom to locate",

  "layout.h": "Horizontal tree",
  "layout.v": "Vertical tree",
  "layout.outline": "Outline",
  "vt.layout.title": "Switch canvas layout (folds/branch/viewport are remembered per layout)",
};
