/** Chinese UI strings — the source of truth for the key set (DECISIONS §16).
 *  Values must stay byte-identical to the previously hardcoded literals so the
 *  zh-selector E2E suite and recorded behaviour don't shift. */

export const zh = {
  // ---- TokenGate -----------------------------------------------------------
  "gate.subtitle": "轻量科研演化地图 · 输入访问令牌打开工作站",
  "gate.token.placeholder": "访问令牌（Bearer token）",
  "gate.open": "打开",
  "gate.opening": "打开…",
  "gate.err.network": "无法连接服务器",
  "gate.note":
    "令牌只保存在页面内存中，刷新后需要重新输入；不会写入 Cookie、localStorage 或 URL。 本应用不需要任何模型 API Key。",

  // ---- EmptyProjects (App.tsx) ----------------------------------------------
  "empty.enter.or.create": "进入一个已有项目，或新建一个：",
  "empty.none": "还没有可用的项目——先创建第一个项目吧。",
  "empty.enter.btn": "进入「{name}」（v{rev}）",
  "empty.name.label": "项目名（1–100）",
  "empty.name.placeholder": "如：富锂锰基正极的循环衰减机制",
  "empty.objective.label": "研究目标（1–4000）",
  "empty.objective.placeholder": "你要回答什么问题？",
  "empty.create.err": "创建项目失败（请检查网络/令牌）",
  "empty.create": "创建项目",
  "empty.creating": "创建中…",
  "empty.refresh": "刷新项目列表",
  "empty.refreshing": "刷新中…",
  "empty.note":
    "项目数据保存在本服务器（SQLite 卷）。创建与编辑走同一条提交协议， 写操作都带令牌名身份（actor），不可伪造。",

  // ---- TopBar ---------------------------------------------------------------
  "topbar.switch.project": "切换项目",
  "topbar.new.project": "+ 项目",
  "topbar.new.project.title": "创建项目",
  "topbar.search.placeholder": "搜索标题/摘要/标签/观察/结论（中文子串可用）",
  "topbar.search.head": "搜索结果（点击 = 展开祖先并定位，不隐藏主树）",
  "topbar.search.count": " · 共 {n}",
  "topbar.search.loading": "检索中…",
  "topbar.search.empty": "无匹配（折叠不影响搜索覆盖）",
  "topbar.new.route": "+ 一级路线",
  "topbar.more.title": "更多：项目设置 / 适应当前图 / 近期变化 / 导出 / AI 接入",
  "topbar.menu.project.settings": "项目设置",
  "topbar.menu.fit": "适应当前图",
  "topbar.menu.show.archived": "显示已归档节点",
  "topbar.menu.hide.archived": "隐藏已归档节点 ✓",
  "topbar.menu.recent": "近期变化 ▾",
  "topbar.menu.no.commits": "暂无提交",
  "topbar.menu.export": "导出",
  "topbar.menu.export.title": "下载完整项目 JSON（含归档与历史）",
  "topbar.menu.ai": "AI 接入说明",
  "topbar.menu.lang.to_en": "切换为 English",
  "topbar.menu.lang.to_zh": "切换为 中文",
  "topbar.refresh": "刷新",
  "topbar.refresh.title": "手动检查记录是否变化",
  "topbar.actor": "身份: {actor}",
  "topbar.actor.title": "本次会话的访问者身份（由令牌决定，不可伪造）",
  "topbar.conn.version": " · v{v}",
  "topbar.conn.project": " · 项目 v{v}",
  "topbar.exit": "退出",
  "topbar.exit.title": "退出（清空页面内存中的令牌，需重新输入）",

  // ---- formatters (used across screens) -------------------------------------
  "common.first.level.node": "一级节点",

  // ---- enum display labels (API enums stay English; DECISIONS §16) ----------
  "status.unexplored": "未探索",
  "status.in_progress": "进行中",
  "status.promising": "有积极迹象",
  "status.supported": "当前条件下支持",
  "status.not_supported": "当前条件下不支持",
  "status.inconclusive": "尚不能判断",
  "kind.question": "问题",
  "kind.idea": "想法",
  "kind.attempt": "尝试",
  "kind.finding": "发现",
  "rel.related": "相关",
  "rel.motivates": "启发",
  "rel.supports": "支持",
  "rel.contradicts": "反对/不支持",
  "rel.depends_on": "依赖",

  // ---- Workspace：toast / 离开守卫 ------------------------------------------
  "ws.activity.load.fail": "关联加载失败",
  "ws.conflict.after.refresh": "刷新后发现同字段冲突，请在详情面板逐项核对",
  "ws.node.load.fail": "节点加载失败",
  "ws.load.fail": "加载失败",
  "ws.updates.loaded": "已载入最新记录",
  "ws.updates.load.fail": "载入更新失败",
  "ws.rebase.done": "已载入新版并重排草稿",
  "ws.rebase.fail": "重载失败",
  "ws.conflict.banner":
    "版本冲突：服务器已更新到 v{v}。你的草稿完整保留；点“载入新版并重排草稿”后再保存，不会静默覆盖他人修改。",
  "ws.conflict.toast": "版本冲突（已有他人提交）",
  "ws.err.missing": "（缺失：{items}）",
  "ws.err.missing.sep": "、",
  "ws.commit.fail": "提交失败",
  "ws.conflicts.unresolved": "还有 {n} 个字段与他人的修改冲突未处理：请在冲突区逐项选择后再保存",
  "ws.draft.stale": "草稿基于 v{base}，服务器已是 v{server}：先点“载入新版并重排草稿”再保存",
  "ws.confirm.draft": "有未保存的草稿。{what}草稿将丢失，确定继续？",
  "ws.confirm.leave.node": "离开当前节点，",
  "ws.confirm.switch.project": "切换项目，",
  "ws.confirm.new.project": "新建项目会离开当前项目，",
  "ws.confirm.exit": "退出当前项目，",
  "ws.created.rev": "已创建（v{v}）",
  "ws.saved.rev": "已保存（v{v}）",
  "ws.create.fail": "创建失败",
  "ws.no.change": "记录目前无变化",
  "ws.refresh.fail": "刷新失败",
  "ws.loading.project": "正在加载项目…",
  "ws.export.done": "导出完成（含归档记录与全部历史）",
  "ws.export.fail": "导出失败",
  "ws.recent.archived": "该提交涉及的对象已归档",

  // ---- Workspace：提交摘要（会进入历史与「近期变化」，用户可见） -------------
  "ws.summary.update": "更新节点：{title}",
  "ws.summary.create.child": "新增子节点：{title}",
  "ws.summary.create.root": "新增一级路线：{title}",
  "ws.summary.move": "移动归属：{title}",
  "ws.summary.move.up": "上移：{title}",
  "ws.summary.move.down": "下移：{title}",
  "ws.summary.archive.node": "归档节点：{title}",
  "ws.summary.restore.node": "恢复节点：{title}",
  "ws.summary.relation.create": "建立关联：{source} {kind} → {target}…",
  "ws.summary.relation.update": "修改关联：{kind}",
  "ws.summary.relation.archive": "归档关联 {kind}",
  "ws.summary.relation.restore": "恢复关联 {kind}",
  "ws.summary.project.update": "更新项目名称与目标",

  // ---- 通用 / 模态共享 --------------------------------------------------------
  "common.cancel": "取消",
  "common.close": "关闭",
  "common.top.level.option": "（项目一级节点）",

  // ---- CreateNodeModal ---------------------------------------------------------
  "kind.finding.long": "发现（含观察/结果）",
  "modal.create.title": "新增节点 · 父级：{parent}",
  "modal.field.title": "标题（1–80）",
  "modal.field.summary": "摘要（一句话研究增量，0–280）",
  "modal.field.tags": "标签（逗号分隔）",
  "modal.gated.hint":
    "状态为「受支持／不支持」时，必须给出适用条件、发现与决定，并至少 1 条证据（与服务端同一闸口）。",
  "modal.field.scope": "适用条件 scope（必填，≤1000）",
  "modal.ph.scope": "该结论适用于哪些材料 / 工艺 / 条件",
  "modal.field.finding": "发现 finding（必填，≤2000）",
  "modal.ph.finding": "观察到的事实与结果，尽量定量",
  "modal.field.decision": "决定 decision（必填，≤2000）",
  "modal.ph.decision": "采纳 / 放弃 / 修改什么条件，以及为什么",
  "modal.field.evidence": "证据（≥1 条）",
  "modal.ev.inline": "行内记录",
  "modal.ev.path": "路径",
  "modal.ev.label.ph": "名称",
  "modal.ph.url": "https://…",
  "modal.ph.path": "相对仓库路径",
  "modal.ph.inline": "内容",
  "modal.ev.remove.title": "删除这条证据",
  "modal.ev.add": "＋ 添加证据",
  "modal.create": "创建",
  "modal.creating": "创建中…",

  // ---- ProjectModal / CreateRelationModal ---------------------------------------
  "modal.project.edit.title": "项目设置（名称与目标）",
  "modal.common.save": "保存",
  "modal.rel.title": "新增关联 · 起点：{from}（方向：本节点 → 目标）",
  "modal.rel.target.label": "选择目标（输入关键词缩小范围）",
  "modal.rel.target.ph": "如：溶剂热 / 高压 / 催化剂",
  "modal.rel.candidates": "— 从 {n} 个候选中选择 —",
  "modal.rel.kind.label": "关系类型（方向固定：本节点 → 目标）",
  "modal.rel.related": "相关 related（无向）",
  "modal.rel.motivates": "启发 motivates",
  "modal.rel.supports": "支持 supports",
  "modal.rel.contradicts": "反对/不支持 contradicts",
  "modal.rel.depends_on": "依赖 depends_on",
  "modal.rel.reason.label": "原因（一句话，1–500，必填）",
  "modal.rel.reason.ph": "例：该失败实验的负结果支持本节点的停止条件",
  "modal.rel.create": "建立关联",
  "modal.rel.note": "新增 supports / contradicts 不会自动改变任何节点状态；状态只能由研究者显式填写。",

  // ---- AiAccessModal --------------------------------------------------------------
  "ai.intro": "AI 与浏览器走同一条提交协议，不需要模型 API Key；所有持令牌者属于同一个受信任空间。",
  "ai.line.server": "服务器：{origin}（Authorization: Bearer <你的令牌>）",
  "ai.line.name": "项目名称：{name}",
  "ai.line.id": "项目 ID：{pid}",
  "ai.line.actor": "身份：每条提交的 actor 为令牌名（token_name），无法伪造",
  "ai.section.setup": "# 一次性配置（令牌只走环境变量，永不写进文件 / 日志 / 命令行参数）",
  "ai.line.token.export": "export RESEARCHMAP_TOKEN=\"<你的令牌>\"",
  "ai.section.read": "# 读取当前状态（不改数据）。以下三条都可直接粘贴运行：",
  "ai.section.focus": "# 聚焦某个节点（节点 ID 见卡片右键「复制节点深链接」末尾的 ?node=，或 graph 输出）：",
  "ai.section.search": "# 按关键词检索（中文子串可用）：",
  "ai.section.commit": "# 提交修改（请求文件必须含完整 request_id + expected_revision；先 --dry-run 校验）",
  "ai.section.409": "# 409 有四种，处理方式不同（退出码统一为 2，具体看 error.code）：",
  "ai.409.rev1": "#   REVISION_CONFLICT      期间有人提交过，锁的是整个项目的版本、不是单个对象；",
  "ai.409.rev2": "#                          本次一个字节都没写入。重读 context 后显式重写文件",
  "ai.409.rev3": "#                          （新的 expected_revision + 合并后的 operations）；",
  "ai.409.rev4": "#                          409 不留记录，沿用原 request_id 是合法的。",
  "ai.409.idem1": "#   IDEMPOTENCY_KEY_REUSED 该 request_id 已以不同内容成功提交过。要么原字节重放，",
  "ai.409.idem2": "#                          要么换新 request_id，切勿改字段后复用。",
  "ai.409.dup": "#   DUPLICATE_RELATION     同端点同类型的未归档关联已存在，改用 relation.update/restore。",
  "ai.409.pag": "#   PAGINATION_STALE       分页途中项目版本变了，放弃游标从头翻。",
  "ai.footer": "# 完整规范：docs/AI_USAGE.md（英文主入口）/ docs/AI_USAGE.zh-CN.md",
  "ai.copied": "接入信息已复制",
  "ai.copy.fail": "复制失败",
  "ai.copy": "复制接入信息",
} as const;

export type DictKey = keyof typeof zh;
