/** English UI strings. The type pins every key of dict.zh — a missing key here
 *  is a compile error, so `npm run build` enforces dictionary parity. */

import type { zh } from "./dict.zh";

export const en: Record<keyof typeof zh, string> = {
  // ---- TokenGate -----------------------------------------------------------
  "gate.subtitle": "Lightweight research evolution map · enter your access token to open the workspace",
  "gate.token.placeholder": "Access token (Bearer token)",
  "gate.open": "Open",
  "gate.opening": "Opening…",
  "gate.err.network": "Cannot reach the server",
  "gate.note":
    "The token is kept in page memory only; a refresh requires re-entry. It is never written to cookies, localStorage, or the URL. This app needs no model API key.",

  // ---- EmptyProjects (App.tsx) ----------------------------------------------
  "empty.enter.or.create": "Enter an existing project, or create one:",
  "empty.none": "No projects yet — create your first project.",
  "empty.enter.btn": "Enter \"{name}\" (v{rev})",
  "empty.name.label": "Project name (1–100)",
  "empty.name.placeholder": "e.g. Li-rich Mn-based cathode degradation mechanism",
  "empty.objective.label": "Research goal (1–4000)",
  "empty.objective.placeholder": "What question are you trying to answer?",
  "empty.create.err": "Failed to create the project (check network/token)",
  "empty.create": "Create project",
  "empty.creating": "Creating…",
  "empty.refresh": "Refresh project list",
  "empty.refreshing": "Refreshing…",
  "empty.note":
    "Project data is stored on this server (SQLite volume). Creation and edits go through the same commit protocol; every write carries the token's identity (actor) and cannot be forged.",

  // ---- TopBar ---------------------------------------------------------------
  "topbar.switch.project": "Switch project",
  "topbar.new.project": "+ Project",
  "topbar.new.project.title": "Create project",
  "topbar.search.placeholder": "Search titles/summaries/tags/observations/findings (substrings work)",
  "topbar.search.head": "Search results (click = expand ancestors and locate; the main tree stays visible)",
  "topbar.search.count": " · {n} total",
  "topbar.search.loading": "Searching…",
  "topbar.search.empty": "No matches (folding does not limit search)",
  "topbar.new.route": "+ Top-level route",
  "topbar.more.title": "More: project settings / fit map / recent changes / export / AI access",
  "topbar.menu.project.settings": "Project settings",
  "topbar.menu.fit": "Fit current map",
  "topbar.menu.show.archived": "Show archived nodes",
  "topbar.menu.hide.archived": "Hide archived nodes ✓",
  "topbar.menu.recent": "Recent changes ▾",
  "topbar.menu.no.commits": "No commits yet",
  "topbar.menu.export": "Export",
  "topbar.menu.export.title": "Download the full project JSON (incl. archive and history)",
  "topbar.menu.ai": "AI access guide",
  "topbar.menu.lang.to_en": "Switch to English",
  "topbar.menu.lang.to_zh": "切换为 中文",
  "topbar.refresh": "Refresh",
  "topbar.refresh.title": "Manually check whether records changed",
  "topbar.actor": "Identity: {actor}",
  "topbar.actor.title": "Who is signed in for this session (decided by the token; cannot be forged)",
  "topbar.conn.version": " · v{v}",
  "topbar.conn.project": " · project v{v}",
  "topbar.exit": "Exit",
  "topbar.exit.title": "Exit (clears the in-memory token; you will re-enter it)",

  // ---- formatters (used across screens) -------------------------------------
  "common.first.level.node": "top-level node",

  // ---- enum display labels ---------------------------------------------------
  "status.unexplored": "Unexplored",
  "status.in_progress": "In progress",
  "status.promising": "Promising",
  "status.supported": "Supported (current conditions)",
  "status.not_supported": "Not supported (current conditions)",
  "status.inconclusive": "Inconclusive",
  "kind.question": "Question",
  "kind.idea": "Idea",
  "kind.attempt": "Attempt",
  "kind.finding": "Finding",
  "rel.related": "Related",
  "rel.motivates": "Motivates",
  "rel.supports": "Supports",
  "rel.contradicts": "Contradicts",
  "rel.depends_on": "Depends on",

  // ---- Workspace: toasts / leave guards --------------------------------------
  "ws.activity.load.fail": "Failed to load relations",
  "ws.conflict.after.refresh": "Same-field conflicts were found after the refresh — review them one by one in the details panel",
  "ws.node.load.fail": "Failed to load the node",
  "ws.load.fail": "Failed to load",
  "ws.updates.loaded": "Latest records loaded",
  "ws.updates.load.fail": "Failed to load updates",
  "ws.rebase.done": "New version loaded and draft rebased",
  "ws.rebase.fail": "Reload failed",
  "ws.conflict.banner":
    "Revision conflict: the server has moved to v{v}. Your draft is fully preserved; click “Load new version and rebase draft” before saving — nothing is silently overwritten.",
  "ws.conflict.toast": "Revision conflict (someone else committed in the meantime)",
  "ws.err.missing": " (missing: {items})",
  "ws.err.missing.sep": ", ",
  "ws.commit.fail": "Commit failed",
  "ws.conflicts.unresolved": "{n} field(s) still conflict with someone else's edits: pick a resolution for each in the conflict area before saving",
  "ws.draft.stale": "Draft is based on v{base} but the server is at v{server}: click “Load new version and rebase draft” first, then save",
  "ws.confirm.draft": "You have an unsaved draft. {what}the draft will be lost. Continue?",
  "ws.confirm.leave.node": "Leaving the current node, ",
  "ws.confirm.switch.project": "Switching project, ",
  "ws.confirm.new.project": "Creating a new project leaves the current one, ",
  "ws.confirm.exit": "Exiting the current project, ",
  "ws.created.rev": "Created (v{v})",
  "ws.saved.rev": "Saved (v{v})",
  "ws.create.fail": "Failed to create",
  "ws.no.change": "Records unchanged so far",
  "ws.refresh.fail": "Refresh failed",
  "ws.loading.project": "Loading project…",
  "ws.export.done": "Export complete (includes archived records and full history)",
  "ws.export.fail": "Export failed",
  "ws.recent.archived": "The objects touched by that commit have been archived",

  // ---- Workspace: commit summaries (land in history and recent changes) ------
  "ws.summary.update": "Update node: {title}",
  "ws.summary.create.child": "Add child node: {title}",
  "ws.summary.create.root": "Add top-level route: {title}",
  "ws.summary.move": "Re-parent: {title}",
  "ws.summary.move.up": "Move up: {title}",
  "ws.summary.move.down": "Move down: {title}",
  "ws.summary.archive.node": "Archive node: {title}",
  "ws.summary.restore.node": "Restore node: {title}",
  "ws.summary.relation.create": "Create relation: {source} {kind} → {target}…",
  "ws.summary.relation.update": "Edit relation: {kind}",
  "ws.summary.relation.archive": "Archive relation {kind}",
  "ws.summary.relation.restore": "Restore relation {kind}",
  "ws.summary.project.update": "Update project name and objective",

  // ---- shared modal / common strings ------------------------------------------
  "common.cancel": "Cancel",
  "common.close": "Close",
  "common.top.level.option": "(project top-level nodes)",

  // ---- CreateNodeModal -----------------------------------------------------------
  "kind.finding.long": "Finding (observations / results)",
  "modal.create.title": "New node · parent: {parent}",
  "modal.field.title": "Title (1–80)",
  "modal.field.summary": "Summary (one-sentence research increment, 0–280)",
  "modal.field.tags": "Tags (comma-separated)",
  "modal.gated.hint":
    "For the statuses “supported / not supported” you must provide scope, finding and decision, plus at least 1 piece of evidence (same gate as the server).",
  "modal.field.scope": "Scope (required, ≤1000)",
  "modal.ph.scope": "Which materials / processes / conditions does this conclusion apply to",
  "modal.field.finding": "Finding (required, ≤2000)",
  "modal.ph.finding": "Observed facts and results, quantitative where possible",
  "modal.field.decision": "Decision (required, ≤2000)",
  "modal.ph.decision": "Adopt / drop / change which conditions, and why",
  "modal.field.evidence": "Evidence (≥1 item)",
  "modal.ev.inline": "Inline note",
  "modal.ev.path": "Path",
  "modal.ev.label.ph": "Name",
  "modal.ph.url": "https://…",
  "modal.ph.path": "Relative repo path",
  "modal.ph.inline": "Content",
  "modal.ev.remove.title": "Remove this evidence item",
  "modal.ev.add": "＋ Add evidence",
  "modal.create": "Create",
  "modal.creating": "Creating…",

  // ---- ProjectModal / CreateRelationModal ------------------------------------------
  "modal.project.edit.title": "Project settings (name and objective)",
  "modal.common.save": "Save",
  "modal.rel.title": "New relation · from: {from} (direction: this node → target)",
  "modal.rel.target.label": "Pick a target (type keywords to narrow down)",
  "modal.rel.target.ph": "e.g. solvothermal / high pressure / catalyst",
  "modal.rel.candidates": "— choose from {n} candidates —",
  "modal.rel.kind.label": "Relation type (direction fixed: this node → target)",
  "modal.rel.related": "Related · related (undirected)",
  "modal.rel.motivates": "Motivates · motivates",
  "modal.rel.supports": "Supports · supports",
  "modal.rel.contradicts": "Contradicts · contradicts",
  "modal.rel.depends_on": "Depends on · depends_on",
  "modal.rel.reason.label": "Reason (one sentence, 1–500, required)",
  "modal.rel.reason.ph": "e.g. the negative result of that failed experiment supports this node's stop condition",
  "modal.rel.create": "Create relation",
  "modal.rel.note": "Creating supports / contradicts never changes any node status; only researchers set statuses explicitly.",

  // ---- AiAccessModal ------------------------------------------------------------------
  "ai.intro": "AI tools use the same commit protocol as the browser and need no model API key; every token holder is part of the same trusted space.",
  "ai.line.server": "Server: {origin} (Authorization: Bearer <your token>)",
  "ai.line.name": "Project name: {name}",
  "ai.line.id": "Project ID: {pid}",
  "ai.line.actor": "Identity: every commit's actor is the token name (token_name) and cannot be forged",
  "ai.section.setup": "# One-time setup (the token only travels through environment variables, never into files / logs / command-line arguments)",
  "ai.line.token.export": "export RESEARCHMAP_TOKEN=\"<your token>\"",
  "ai.section.read": "# Read the current state (no writes). All three commands below can be pasted and run as-is:",
  "ai.section.focus": "# Focus a node (the node ID is at the end of the ?node= from the card's right-click “Copy node deep link”, or in the graph output):",
  "ai.section.search": "# Search by keyword (CJK substrings work):",
  "ai.section.commit": "# Commit changes (the request file must contain a complete request_id + expected_revision; validate with --dry-run first)",
  "ai.section.409": "# There are four kinds of 409, handled differently (exit code is always 2; check error.code):",
  "ai.409.rev1": "#   REVISION_CONFLICT      someone committed in the meantime; the lock covers the whole project's revision, not a single object;",
  "ai.409.rev2": "#                          not a single byte was written this time. Re-read context, then explicitly rewrite the file",
  "ai.409.rev3": "#                          (new expected_revision + the merged operations);",
  "ai.409.rev4": "#                          a 409 leaves no record, so reusing the original request_id is legal.",
  "ai.409.idem1": "#   IDEMPOTENCY_KEY_REUSED this request_id already succeeded with different content. Either replay the original bytes,",
  "ai.409.idem2": "#                          or use a new request_id — never reuse it after editing fields.",
  "ai.409.dup": "#   DUPLICATE_RELATION     an unarchived relation with the same endpoints and type already exists; use relation.update/restore.",
  "ai.409.pag": "#   PAGINATION_STALE       the project revision changed mid-pagination; drop the cursor and page from the start.",
  "ai.footer": "# Full spec: docs/AI_USAGE.md (English entry) / docs/AI_USAGE.zh-CN.md",
  "ai.copied": "Access info copied",
  "ai.copy.fail": "Copy failed",
  "ai.copy": "Copy access info",
};
